export interface MetricInfo {
  label: string;
  description: string;
  unit: "currency" | "percent" | "number" | "ratio" | "months";
}

export const metricDescriptions: Record<string, MetricInfo> = {
  // ─── Shared / P&L ────────────────────────────────────────────────────────────
  "Gross Revenue": {
    label: "Gross Revenue",
    description: "Total revenue before any deductions such as commissions, returns, or discounts",
    unit: "currency",
  },
  "Net Revenue": {
    label: "Net Revenue",
    description: "Revenue remaining after platform commissions, payment processing fees, and refunds",
    unit: "currency",
  },
  "COGS": {
    label: "COGS",
    description: "Cost of Goods Sold — direct costs attributable to producing or delivering the product",
    unit: "currency",
  },
  "Gross Profit": {
    label: "Gross Profit",
    description: "Net Revenue minus COGS; profit before operating expenses",
    unit: "currency",
  },
  "EBITDA": {
    label: "EBITDA",
    description: "Earnings Before Interest, Taxes, Depreciation, and Amortization; a proxy for operating cash flow",
    unit: "currency",
  },
  "Net Profit": {
    label: "Net Profit",
    description: "Bottom-line profit after all expenses and corporate tax",
    unit: "currency",
  },
  "Corporate Tax": {
    label: "Corporate Tax",
    description: "Tax liability applied to taxable income at the configured corporate tax rate",
    unit: "currency",
  },
  "Cash Balance": {
    label: "Cash Balance",
    description: "Running cash on hand after accounting for all inflows and outflows each month",
    unit: "currency",
  },
  "Burn Rate": {
    label: "Burn Rate",
    description: "Net cash consumed per month; positive when spending exceeds revenue",
    unit: "currency",
  },
  "Runway (Months)": {
    label: "Runway (Months)",
    description: "Number of months of cash remaining at the current burn rate before funds are exhausted",
    unit: "months",
  },
  "ROI %": {
    label: "ROI %",
    description: "Return on Investment — cumulative net profit divided by total capital invested, expressed as a percentage",
    unit: "percent",
  },
  "Cumulative Revenue": {
    label: "Cumulative Revenue",
    description: "Running total of gross revenue from the start of the model through the current month",
    unit: "currency",
  },
  "Cumulative Net Profit": {
    label: "Cumulative Net Profit",
    description: "Running total of net profit (or loss) from the start of the model through the current month",
    unit: "currency",
  },
  "Marketing": {
    label: "Marketing",
    description: "Total marketing spend including paid advertising and organic acquisition costs",
    unit: "currency",
  },
  "Salaries": {
    label: "Salaries",
    description: "Total monthly salary expense across all phases",
    unit: "currency",
  },
  "Misc Costs": {
    label: "Misc Costs",
    description: "Miscellaneous operating costs not captured in other expense line items",
    unit: "currency",
  },
  "Total Expenses": {
    label: "Total Expenses",
    description: "Sum of all operating expenses including COGS, marketing, salaries, and miscellaneous costs",
    unit: "currency",
  },
  "Gross Margin %": {
    label: "Gross Margin %",
    description: "Gross Profit as a percentage of Net Revenue; measures production and delivery efficiency",
    unit: "percent",
  },
  "LTV": {
    label: "LTV",
    description: "Customer Lifetime Value — projected total revenue generated by a customer over their entire relationship with the business",
    unit: "currency",
  },
  "LTV/CAC": {
    label: "LTV/CAC",
    description: "Ratio of Customer Lifetime Value to Customer Acquisition Cost; values above 3x indicate a healthy unit economics profile",
    unit: "ratio",
  },
  "CAC": {
    label: "CAC",
    description: "Customer Acquisition Cost — total marketing spend divided by the number of new customers acquired in a given period",
    unit: "currency",
  },
  "ROAS": {
    label: "ROAS",
    description: "Return on Ad Spend — revenue generated per dollar of advertising expenditure in a given month",
    unit: "ratio",
  },
  "Cumulative ROAS": {
    label: "Cumulative ROAS",
    description: "Total revenue generated to date divided by total advertising spend to date",
    unit: "ratio",
  },

  // ─── Subscription-specific ───────────────────────────────────────────────────
  "Total MRR": {
    label: "Total MRR",
    description: "Total Monthly Recurring Revenue across all subscription tiers and billing cadences",
    unit: "currency",
  },
  "MRR Weekly": {
    label: "MRR Weekly",
    description: "Monthly Recurring Revenue contribution from weekly-billing subscribers",
    unit: "currency",
  },
  "MRR Monthly": {
    label: "MRR Monthly",
    description: "Monthly Recurring Revenue contribution from monthly-billing subscribers",
    unit: "currency",
  },
  "MRR Annual": {
    label: "MRR Annual",
    description: "Monthly Recurring Revenue contribution from annual-billing subscribers (amortized monthly)",
    unit: "currency",
  },
  "New MRR": {
    label: "New MRR",
    description: "MRR added from newly acquired paying subscribers in the current month",
    unit: "currency",
  },
  "Expansion MRR": {
    label: "Expansion MRR",
    description: "MRR gained from existing subscribers upgrading to higher-tier plans",
    unit: "currency",
  },
  "Contraction MRR": {
    label: "Contraction MRR",
    description: "MRR lost from existing subscribers downgrading to lower-tier plans",
    unit: "currency",
  },
  "Churned MRR": {
    label: "Churned MRR",
    description: "MRR lost from subscribers who cancelled their subscription entirely",
    unit: "currency",
  },
  "Net New MRR": {
    label: "Net New MRR",
    description: "Net change in MRR: New + Expansion minus Contraction minus Churned",
    unit: "currency",
  },
  "NRR %": {
    label: "NRR %",
    description: "Net Revenue Retention — measures revenue retained from existing customers including expansion and churn; values above 100% indicate net growth from the existing base",
    unit: "percent",
  },
  "Quick Ratio": {
    label: "Quick Ratio",
    description: "MRR growth efficiency: (New + Expansion MRR) divided by (Contraction + Churned MRR); values above 4 indicate strong growth relative to churn",
    unit: "ratio",
  },
  "ARPU": {
    label: "ARPU",
    description: "Average Revenue Per User — total MRR divided by total active subscribers",
    unit: "currency",
  },
  "Blended Churn": {
    label: "Blended Churn",
    description: "Weighted average churn rate across all subscription plan types (weekly, monthly, annual)",
    unit: "percent",
  },
  "CRR %": {
    label: "CRR %",
    description: "Customer Retention Rate — percentage of subscribers retained from one period to the next",
    unit: "percent",
  },
  "Active Users": {
    label: "Active Users",
    description: "Total number of active paying subscribers at the end of the current month",
    unit: "number",
  },
  "New Paid Users": {
    label: "New Paid Users",
    description: "Number of new subscribers who converted to paid plans in the current month",
    unit: "number",
  },
  "Installs": {
    label: "Installs",
    description: "Total app installs (paid + organic) in the current month",
    unit: "number",
  },
  "CPI": {
    label: "CPI",
    description: "Cost Per Install — average advertising spend required to acquire one app install",
    unit: "currency",
  },
  "Payback Period": {
    label: "Payback Period",
    description: "Number of months required to recover the Customer Acquisition Cost from a subscriber's monthly revenue contribution",
    unit: "months",
  },
  "Revenue per Install": {
    label: "Revenue per Install",
    description: "Total revenue generated per install, accounting for trial and paid conversion rates",
    unit: "currency",
  },
  "CAE": {
    label: "CAE",
    description: "Cost per Active Engagement — blended cost to acquire one active paying user, including both paid and organic channels",
    unit: "currency",
  },
  "Weekly Churn %": {
    label: "Weekly Churn %",
    description: "Monthly cancellation rate among weekly-billing subscribers",
    unit: "percent",
  },
  "Monthly Churn %": {
    label: "Monthly Churn %",
    description: "Monthly cancellation rate among monthly-billing subscribers",
    unit: "percent",
  },
  "Annual Churn %": {
    label: "Annual Churn %",
    description: "Annualized non-renewal rate among annual-billing subscribers",
    unit: "percent",
  },

  // ─── Ecommerce-specific ───────────────────────────────────────────────────────
  "AOV": {
    label: "AOV",
    description: "Average Order Value — mean revenue per order before discounts and returns",
    unit: "currency",
  },
  "Total Orders": {
    label: "Total Orders",
    description: "Total number of orders placed in the current month across new and returning customers",
    unit: "number",
  },
  "New Customers": {
    label: "New Customers",
    description: "Number of first-time buyers acquired in the current month",
    unit: "number",
  },
  "Returning Orders": {
    label: "Returning Orders",
    description: "Orders placed by previously acquired customers in the current month",
    unit: "number",
  },
  "Cumulative Customers": {
    label: "Cumulative Customers",
    description: "Total unique customers acquired from the start of the model through the current month",
    unit: "number",
  },
  "Repeat Rate %": {
    label: "Repeat Rate %",
    description: "Percentage of customers who place at least one additional order after their first purchase",
    unit: "percent",
  },
  "Returns": {
    label: "Returns",
    description: "Revenue lost to product returns and refunds in the current month",
    unit: "currency",
  },
  "Discounts": {
    label: "Discounts",
    description: "Total discount value applied to orders in the current month",
    unit: "currency",
  },
  "CAC Payback": {
    label: "CAC Payback",
    description: "Number of months needed to recover the customer acquisition cost through gross profit contribution",
    unit: "months",
  },

  // ─── SaaS-specific ────────────────────────────────────────────────────────────
  "ARR": {
    label: "ARR",
    description: "Annual Recurring Revenue — total MRR multiplied by 12; the primary growth metric for B2B SaaS businesses",
    unit: "currency",
  },
  "Active Customers": {
    label: "Active Customers",
    description: "Number of active paying customer accounts (logos) at the end of the current month",
    unit: "number",
  },
  "Active Seats": {
    label: "Active Seats",
    description: "Total number of active licensed seats across all customer accounts",
    unit: "number",
  },
  "GRR %": {
    label: "GRR %",
    description: "Gross Revenue Retention — percentage of recurring revenue retained from existing customers, excluding any expansion; measures pure churn impact",
    unit: "percent",
  },
  "Rule of 40": {
    label: "Rule of 40",
    description: "Sum of revenue growth rate and EBITDA margin; a score above 40% indicates a healthy balance between growth and profitability",
    unit: "percent",
  },
  "Magic Number": {
    label: "Magic Number",
    description: "Net New ARR generated per dollar of Sales & Marketing spend; values above 1.0 indicate efficient go-to-market execution",
    unit: "ratio",
  },
  "ARPA": {
    label: "ARPA",
    description: "Average Revenue Per Account — total MRR divided by the number of active customer accounts",
    unit: "currency",
  },
  "New Deals": {
    label: "New Deals",
    description: "Number of new customer accounts closed in the current month",
    unit: "number",
  },
  "Total Leads": {
    label: "Total Leads",
    description: "Total inbound and outbound leads generated in the current month across paid and organic channels",
    unit: "number",
  },
  "Demos": {
    label: "Demos",
    description: "Number of product demonstrations conducted in the current month",
    unit: "number",
  },
  "Expansion Seats": {
    label: "Expansion Seats",
    description: "Net new seats added by existing customers through upgrades or additional licenses in the current month",
    unit: "number",
  },
  "Contraction Seats": {
    label: "Contraction Seats",
    description: "Seats removed by existing customers through downgrades or license reductions in the current month",
    unit: "number",
  },
  "Churned Customers": {
    label: "Churned Customers",
    description: "Number of customer accounts that cancelled their subscription entirely in the current month",
    unit: "number",
  },
  "CPL": {
    label: "CPL",
    description: "Cost Per Lead — total marketing spend divided by the number of leads generated in the current month",
    unit: "currency",
  },
  "Organic %": {
    label: "Organic %",
    description: "Percentage of leads generated through organic channels (content, SEO, referrals) as opposed to paid advertising",
    unit: "percent",
  },
};
